/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_questdot_ndkexample_TestNDK */

#ifndef _Included_com_example_questdot_ndkexample_TestNDK
#define _Included_com_example_questdot_ndkexample_TestNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_questdot_ndkexample_TestNDK
 * Method:    getNDKString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_questdot_ndkexample_TestNDK_getNDKString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
